In [1]:
import pandas as pd

In [2]:
matches = pd.read_csv("matches.csv", index_col=0)

In [3]:
matches.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
0,2023-08-13,16:30,Premier League,Matchweek 1,Sun,Away,D,1.0,1.0,Chelsea,...,Match Report,NaN,13.0,1.0,17.8,0.0,0,0,2023,Liverpool
1,2023-08-19,15:00,Premier League,Matchweek 2,Sat,Home,W,3.0,1.0,Bournemouth,...,Match Report,NaN,25.0,9.0,16.8,1.0,0,1,2023,Liverpool
2,2023-08-27,16:30,Premier League,Matchweek 3,Sun,Away,W,2.0,1.0,Newcastle Utd,...,Match Report,NaN,9.0,4.0,17.2,1.0,0,0,2023,Liverpool
3,2023-09-03,14:00,Premier League,Matchweek 4,Sun,Home,W,3.0,0.0,Aston Villa,...,Match Report,NaN,17.0,4.0,14.7,0.0,0,0,2023,Liverpool
4,2023-09-16,12:30,Premier League,Matchweek 5,Sat,Away,W,3.0,1.0,Wolves,...,Match Report,NaN,16.0,5.0,15.8,0.0,0,0,2023,Liverpool

In [5]:
matches['team'].value_counts()

Liverpool                   54
Fulham                      54
Everton                     54
Nottingham Forest           54
Crystal Palace              54
Bournemouth                 54
Wolverhampton Wanderers     54
Arsenal                     54
Brentford                   54
Chelsea                     54
West Ham United             54
Brighton and Hove Albion    54
Newcastle United            54
Manchester United           54
Tottenham Hotspur           54
Manchester City             54
Aston Villa                 54
Leicester City              38
Leeds United                38
Southampton                 38
Luton Town                  16
Burnley                     16
Sheffield United            16
Name: team, dtype: int64

In [6]:
matches["round"].value_counts()

Matchweek 1     40
Matchweek 10    40
Matchweek 2     40
Matchweek 16    40
Matchweek 15    40
Matchweek 13    40
Matchweek 12    40
Matchweek 11    40
Matchweek 14    40
Matchweek 9     40
Matchweek 7     40
Matchweek 6     40
Matchweek 5     40
Matchweek 4     40
Matchweek 8     40
Matchweek 3     40
Matchweek 28    20
Matchweek 31    20
Matchweek 33    20
Matchweek 34    20
Matchweek 37    20
Matchweek 35    20
Matchweek 36    20
Matchweek 32    20
Matchweek 29    20
Matchweek 30    20
Matchweek 20    20
Matchweek 27    20
Matchweek 26    20
Matchweek 25    20
Matchweek 24    20
Matchweek 23    20
Matchweek 22    20
Matchweek 21    20
Matchweek 19    20
Matchweek 18    20
Matchweek 17    20
Matchweek 38    20
Name: round, dtype: int64

In [7]:
matches["venue_code"] = matches["venue"].astype("category").cat.codes

In [8]:
matches["opp_code"] = matches["opponent"].astype("category").cat.codes

In [9]:
matches["hour"] = matches["time"].str.replace(":.+", "", regex=True).astype("int")

In [11]:
matches["date"] = pd.to_datetime(matches["date"])

In [12]:
matches["day_code"] = matches["date"].dt.dayofweek

In [13]:
matches["target"] = (matches["result"] == "W").astype("int")

In [14]:
matches

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
0,2023-08-13,16:30,Premier League,Matchweek 1,Sun,Away,D,1.0,1.0,Chelsea,...,0.0,0,0,2023,Liverpool,0,6,16,6,0
1,2023-08-19,15:00,Premier League,Matchweek 2,Sat,Home,W,3.0,1.0,Bournemouth,...,1.0,0,1,2023,Liverpool,1,2,15,5,1
2,2023-08-27,16:30,Premier League,Matchweek 3,Sun,Away,W,2.0,1.0,Newcastle Utd,...,1.0,0,0,2023,Liverpool,0,16,16,6,1
3,2023-09-03,14:00,Premier League,Matchweek 4,Sun,Home,W,3.0,0.0,Aston Villa,...,0.0,0,0,2023,Liverpool,1,1,14,6,1
4,2023-09-16,12:30,Premier League,Matchweek 5,Sat,Away,W,3.0,1.0,Wolves,...,0.0,0,0,2023,Liverpool,0,22,12,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42,2023-04-30,14:00,Premier League,Matchweek 34,Sun,Away,L,1.0,3.0,Newcastle Utd,...,0.0,0,0,2022,Southampton,0,16,14,6,0
43,2023-05-08,20:00,Premier League,Matchweek 35,Mon,Away,L,3.0,4.0,Nott'ham Forest,...,0.0,1,1,2022,Southampton,0,17,20,0,0
44,2023-05-13,15:00,Premier League,Matchweek 36,Sat,Home,L,0.0,2.0,Fulham,...,0.0,0,0,2022,Southampton,1,9,15,5,0
45,2023-05-21,14:00,Premier League,Matchweek 37,Sun,Away,L,1.0,3.0,Brighton,...,1.0,0,0,2022,Southampton,0,4,14,6,0
46,2023-05-28,16:30,Premier League,Matchweek 38,Sun,Home,D,4.0,4.0,Liverpool,...,1.0,0,0,2022,Southampton,1,12,16,6,0

In [15]:
del matches["comp"]

In [16]:
del matches["notes"]

In [17]:
from sklearn.ensemble import RandomForestClassifier

In [18]:
rf = RandomForestClassifier(n_estimators=50, min_samples_split=10, random_state=1)

In [19]:
train = matches[matches["date"] < '2023-01-01']

test = matches[matches["date"] > '2023-01-01']

In [20]:
predictors = ["venue_code", "opp_code", "hour", "day_code"]

In [21]:
rf.fit(train[predictors], train["target"])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [22]:
preds = rf.predict(test[predictors])

In [23]:
from sklearn.metrics import accuracy_score

In [28]:
ac = accuracy_score(test["target"], preds)

In [29]:
ac

0.6163101604278075

In [26]:
combined = pd.DataFrame(dict(actual=test["target"], predicted=preds))

pd.crosstab(index=combined["actual"], columns=combined["predicted"])

predicted    0    1
actual
0          357   97
1          190  104

In [27]:
from sklearn.metrics import precision_score

precision_score(test["target"], preds)

0.5174129353233831